In [1]:
import numpy as np

In [56]:
b = np.array([1,2,3,4,5,6,7,8,81])
b.shape
print (b)
b = b.reshape(3,3)
print (b)
b = np.argsort(b)
print (b)
c = np.array([1,2,3,4,5,6,7,8,81])
c = c.reshape(3,3)
print (b+c)
print(b*c)


[ 1  2  3  4  5  6  7  8 81]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 81]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 83]]
[[  0   2   6]
 [  0   5  12]
 [  0   8 162]]
